package ru.apshheko.ttvicuesoft.di.features

import dagger.Component
import ru.apshheko.video_player_screen.di.VideoPlayerScreenDependencies
import ru.apshheko.video_player_screen.di.VideoPlayerScreenFeatureApi

@Component
interface VideoPlayerScreenExportComponent : VideoPlayerScreenDependencies